Add assertions for header presence without checking for a specific value
kotest/kotest-assertions-ktor pull request #30
Opened 2024-05-28 18:11 UTC by jedesroches

Also, while I was in the code:

* write tests for the commonMain source set using the new
  testApplication{} syntax from KTor.
* Factor common code in matchers and in tests
* Write tests for Version and ContentType matchers in commonMain.

2024-06-01 09:07 UTC, Kantis requested changes

2024-06-01 09:07 UTC, Kantis commented on src/commonMain/kotlin/io/kotest/assertions/ktor/client/response.kt
> +private fun haveVersion(version: HttpProtocolVersion) = object : Matcher<HttpResponse> {
We can't make these private. There might be users that use the matchers directly

2024-06-01 09:07 UTC, Kantis commented on src/commonMain/kotlin/io/kotest/assertions/ktor/client/response.kt
> +infix fun HttpResponse.shouldHaveCacheControl(cacheControl: String) =
Please add a newline between unrelated functions

2024-12-15 08:36 UTC, sksamuel commented
I've rebased this onto the main repo and applied it. Appreciate the PR. Sorry for delay.
https://github.com/kotest/kotest/commit/adee80c7273ed03f28cfb266d51f20183845b85a

2024-12-15 08:36 UTC, closed without merging